# Generated by Django 4.2.7 on 2023-11-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PuntajeSeccion1', models.FloatField()),
                ('PuntajeSeccion2', models.FloatField()),
                ('PuntajeSeccion3', models.FloatField()),
                ('PuntajeSeccion4', models.FloatField()),
                ('PuntajeSeccion5', models.FloatField()),
                ('PuntajeSeccion6', models.FloatField()),
                ('PuntajeSeccion7', models.FloatField()),
                ('PuntajeSeccion8', models.FloatField()),
                ('PuntajeSeccion9', models.FloatField()),
                ('PuntajeSeccion10', models.FloatField()),
                ('PuntajeSeccion11', models.FloatField()),
                ('PuntajeSeccion12', models.FloatField()),
                ('PuntajeSeccion13', models.FloatField()),
                ('PuntajeSeccion14', models.FloatField()),
                ('PuntajeTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
